# Default values for rabbit2kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

globals:
  env: reg

image:
  repository: containers.mpi-internal.com/yapo/rabbit2kafka
  tag: ""
  pullPolicy: Always
  pullSecret: containers-mpi-internal-com

secrets:
  resource-kafka-rabbit2kafka:
    KAFKA_HOST: HOST
    KAFKA_PORT: PORT
    KAFKA_TOPIC: TOPIC
  resource-rabbitmq-rabbit2kafka:
    RABBITMQ_HOST: HOST
    RABBITMQ_PORT: PORT
    RABBITMQ_USER: USER
    RABBITMQ_PASSWORD: PASS
    RABBITMQ_QUEUE: QUEUE
    RABBITMQ_EXCHANGE: EXCHANGE
    RABBITMQ_EXCHANGE_TYPE: EXCHANGE_TYPE
    RABBITMQ_VHOST: VHOST

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

prometheus:
  enabled: "false"

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
