sudo: true
os: trusty
language: go

services:
  - docker

go:
  - 1.9
  - master

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

env:
  global:
    - BRANCH=$([ ${TRAVIS_BRANCH} == master ] && echo latest || echo ${TRAVIS_BRANCH})

before_install:
  - configure_jfrog_client
  - helm init --client-only

install:
  - make setup

# script always run to completion (set +e). All of these code checks are must haves
# in a modern Go project.
#script:
#- make validate

after_failure:
  - reports-publisher

after_success:
  - reports-publisher

deploy:
  - provider: script
    script: make docker-build docker-publish
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: script
    script:  make helm-publish
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST = false
